### ISSUE TITLE
Failed to load url /service-worker.js (resolved id: /service-worker.js). Does the file exist?

### ISSUE THREAD

**Issue by pascalandy** [posva/vite-tailwind-starter#146]
```
➜  vite-tailwind-starter git:(master) ✗ yarn dev
yarn run v1.22.4
$ vite
vue-scoped: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
trim: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
vue-scoped: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration

  Vite dev server running at:

  > Local:    http://localhost:3000/
  > Network:  http://192.168.50.239:3000/
  > Network:  http://10.67.143.122:3000/

  ready in 274ms.

postcss-functions: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
postcss-plugin-purgecss: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
9:38:23 p.m. [vite] Internal server error: Failed to load url /service-worker.js (resolved id: /service-worker.js). Does the file exist?
      at transformRequest (/Volumes/960G/_pascalandy/11_FirePress/Github/random-stuff/posva/vite-tailwind-starter/node_modules/vite/dist/node/chunks/dep-3c926c03.js:59215:15)
      at async /Volumes/960G/_pascalandy/11_FirePress/Github/random-stuff/posva/vite-tailwind-starter/node_modules/vite/dist/node/chunks/dep-3c926c03.js:59314:32
9:38:31 p.m. [vite] Internal server error: Failed to load url /service-worker.js (resolved id: /service-worker.js). Does the file exist?
      at transformRequest (/Volumes/960G/_pascalandy/11_FirePress/Github/random-stuff/posva/vite-tailwind-starter/node_modules/vite/dist/node/chunks/dep-3c926c03.js:59215:15)
      at async /Volumes/960G/_pascalandy/11_FirePress/Github/random-stuff/posva/vite-tailwind-starter/node_modules/vite/dist/node/chunks/dep-3c926c03.js:59314:32 (x2)
9:38:42 p.m. [vite] hmr update /src/views/Home.vue
9:38:51 p.m. [vite] hmr update /src/views/Home.vue (x2)
```

![Screen Shot 2021-01-21 at 9 45 39 PM](https://user-images.githubusercontent.com/6694151/105439028-1677c400-5c32-11eb-8e12-0689e0682102.jpg)

**Comment by posva** [comment]
That's probably a leftover from a different version or server, clean the application data and restart the server:

<img width="910" alt="Screenshot 2021-01-22 at 10 29 23" src="https://user-images.githubusercontent.com/664177/105472859-b407dd80-5c9c-11eb-9217-00097c6eadde.png">

**Comment by pascalandy** [comment]
Thanks!
